//! The keystore vectors (`vectors/sdk/S07-keystore.jsonl`, generated by
//! `tools/oracle/gen-keystore-vectors.js` with an independent JavaScript implementation of the
//! format as the oracle) run through the crate's public API.
//!
//! The same tests run natively and in WebAssembly under Node:
//!
//! ```sh
//! cargo test -p iceroot-keystore
//! CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER=wasm-bindgen-test-runner \
//!   cargo test -p iceroot-keystore --target wasm32-unknown-unknown
//! ```
//!
//! Records name their bounds: `standard` is [`Bounds::STANDARD`], `test` is [`Bounds::TEST`]
//! (the floor lowered to Argon2's minimums, feature `testing`), which keeps most vectors fast.

// Tests may panic on a broken vector: that is how they fail.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]

use std::collections::BTreeMap;

use iceroot_keystore::{
    Bounds, Error, Header, Params, Payload, PayloadKind, armor, dearmor, decrypt_with_bounds,
    encrypt_with_salt_and_nonce, inspect,
};
use serde_json::{Value, json};

#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
use wasm_bindgen_test::wasm_bindgen_test as test;

const FILE: &str = include_str!("../../../vectors/sdk/S07-keystore.jsonl");
const CLASS: &str = "S07-keystore";

struct Record {
    line: usize,
    op: String,
    name: String,
    input: Value,
    expected: Result<Value, Value>,
}

fn records() -> (Value, Vec<Record>) {
    let mut lines = FILE.lines().enumerate();
    let (_, first) = lines.next().expect("a meta record");
    let meta: Value = serde_json::from_str(first).expect("JSON");
    assert_eq!(meta["op"], "meta");
    assert_eq!(meta["format"], "heartwood-vectors/1");
    assert_eq!(meta["class"], CLASS);
    let records: Vec<Record> = lines
        .map(|(index, text)| {
            let value: Value = serde_json::from_str(text).expect("JSON");
            assert_eq!(value["network"], "any", "line {}", index + 1);
            assert_eq!(value["height"], 0, "line {}", index + 1);
            let expected = match (value.get("output"), value.get("error")) {
                (Some(output), None) => Ok(output.clone()),
                (None, Some(error)) => Err(error.clone()),
                _ => panic!("line {}: exactly one of output and error", index + 1),
            };
            Record {
                line: index + 1,
                op: value["op"].as_str().expect("an op").to_owned(),
                name: value["name"].as_str().expect("a name").to_owned(),
                input: value["input"].clone(),
                expected,
            }
        })
        .collect();
    assert_eq!(meta["records"].as_u64(), Some(records.len() as u64));
    (meta, records)
}

fn text(value: &Value) -> &str {
    value.as_str().expect("a string")
}

fn bytes(value: &Value) -> Vec<u8> {
    hex::decode(text(value)).expect("hex")
}

fn array<const N: usize>(value: &Value) -> [u8; N] {
    bytes(value).try_into().expect("the length")
}

fn number(value: &Value) -> u32 {
    u32::try_from(value.as_u64().expect("a number")).expect("a u32")
}

fn params(value: &Value) -> Params {
    Params::new(
        number(&value["memoryKib"]),
        number(&value["iterations"]),
        number(&value["parallelism"]),
    )
}

fn bounds(value: &Value) -> Bounds {
    match text(value) {
        "standard" => Bounds::STANDARD,
        "test" => Bounds::TEST,
        other => panic!("unknown bounds {other}"),
    }
}

fn kind(value: &Value) -> PayloadKind {
    match text(value) {
        "bip39-entropy" => PayloadKind::Bip39Entropy,
        "ml-dsa-65-seed" => PayloadKind::MlDsa65Seed,
        other => panic!("unknown payload kind {other}"),
    }
}

/// The keystore of a decrypt or inspect record: its bytes, or its text form.
fn keystore(input: &Value) -> Result<Vec<u8>, Error> {
    match input.get("keystore") {
        Some(value) => Ok(bytes(value)),
        None => dearmor(text(&input["text"])),
    }
}

fn header_json(header: &Header, keystore: &[u8]) -> Value {
    let params = header.params();
    json!({
        "version": header.version(),
        "kdf": header.kdf().as_str(),
        "memoryKib": params.memory_kib(),
        "iterations": params.iterations(),
        "parallelism": params.parallelism(),
        "salt": hex::encode(header.salt()),
        "nonce": hex::encode(header.nonce()),
        "payloadKind": header.payload_kind().as_str(),
        "payloadLength": header.payload_len(),
        "keystoreLength": keystore.len(),
    })
}

fn opened_json(payload: &Payload) -> Value {
    let mut value = json!({
        "kind": payload.kind().as_str(),
        "secret": hex::encode(payload.secret_bytes()),
    });
    if let Some(words) = payload.word_count() {
        value["wordCount"] = json!(words);
    }
    value
}

/// Run one record: the SDK's outcome as the JSON the oracle recorded.
fn run(record: &Record) -> Result<Value, Error> {
    let input = &record.input;
    match record.op.as_str() {
        "keystore.encrypt" => {
            let payload = Payload::new(kind(&input["kind"]), &bytes(&input["secret"]))?;
            let keystore = encrypt_with_salt_and_nonce(
                &payload,
                text(&input["password"]),
                params(&input["params"]),
                &array(&input["salt"]),
                &array(&input["nonce"]),
                &bounds(&input["bounds"]),
            )?;
            // What was written reads back, in both forms.
            let header = inspect(&keystore).expect("a keystore inspects");
            assert_eq!(header.params(), params(&input["params"]));
            assert_eq!(dearmor(&armor(&keystore)).expect("its text"), keystore);
            Ok(json!({ "keystore": hex::encode(&keystore), "text": armor(&keystore) }))
        }
        "keystore.decrypt" => {
            let keystore = keystore(input)?;
            let payload = decrypt_with_bounds(
                &keystore,
                text(&input["password"]),
                &bounds(&input["bounds"]),
            )?;
            Ok(opened_json(&payload))
        }
        "keystore.inspect" => {
            let keystore = keystore(input)?;
            let header = inspect(&keystore)?;
            Ok(header_json(&header, &keystore))
        }
        "keystore.dearmor" => {
            let keystore = dearmor(text(&input["text"]))?;
            Ok(json!({ "keystore": hex::encode(keystore) }))
        }
        "keystore.checkParams" => {
            bounds(&input["bounds"]).check(&params(&input["params"]))?;
            Ok(json!({ "ok": true }))
        }
        other => panic!("unknown operation {other}"),
    }
}

/// Compare an outcome with the record: the output exactly, or the error's code and details (its
/// message is the oracle's own text).
fn compare(record: &Record, outcome: &Result<Value, Error>) -> Option<String> {
    match (&record.expected, outcome) {
        (Ok(expected), Ok(actual)) if expected == actual => None,
        (Err(expected), Err(error))
            if expected["class"] == error.code() && expected["details"] == error.details() =>
        {
            None
        }
        (expected, actual) => Some(format!(
            "{CLASS}:{} {} {:?}: expected {expected:?}, got {:?}",
            record.line,
            record.op,
            record.name,
            actual
                .as_ref()
                .map(|value| value.to_string())
                .map_err(|error| format!("{} {} ({error})", error.code(), error.details()))
        )),
    }
}

#[test]
fn s07_keystore() {
    let (_, records) = records();
    let mut tally: BTreeMap<String, usize> = BTreeMap::new();
    let mut failures = Vec::new();
    for record in &records {
        let outcome = run(record);
        match compare(record, &outcome) {
            None => {
                let verdict = match &outcome {
                    Ok(_) => "ok",
                    Err(error) => error.code(),
                };
                *tally.entry(format!("{} {verdict}", record.op)).or_default() += 1;
            }
            Some(failure) => failures.push(failure),
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
    // Every record is accounted for, so a new one is never passed over without a change here.
    let expected: BTreeMap<String, usize> = [
        ("keystore.checkParams ParamsOutOfRange", 3),
        ("keystore.checkParams ok", 9),
        ("keystore.dearmor Malformed", 18),
        ("keystore.dearmor ok", 4),
        ("keystore.decrypt InvalidPassword", 2),
        ("keystore.decrypt Malformed", 12),
        ("keystore.decrypt ParamsOutOfRange", 20),
        ("keystore.decrypt UnsupportedKdf", 2),
        ("keystore.decrypt UnsupportedPayload", 3),
        ("keystore.decrypt UnsupportedVersion", 3),
        ("keystore.decrypt WrongPasswordOrCorrupt", 17),
        ("keystore.decrypt ok", 13),
        ("keystore.encrypt InvalidPassword", 2),
        ("keystore.encrypt InvalidPayload", 3),
        ("keystore.encrypt ParamsOutOfRange", 2),
        ("keystore.encrypt UnsupportedPayload", 1),
        ("keystore.encrypt ok", 10),
        ("keystore.inspect Malformed", 4),
        ("keystore.inspect UnsupportedKdf", 1),
        ("keystore.inspect UnsupportedPayload", 1),
        ("keystore.inspect UnsupportedVersion", 1),
        ("keystore.inspect ok", 5),
    ]
    .into_iter()
    .map(|(key, count)| (key.to_owned(), count))
    .collect();
    assert_eq!(tally, expected);
}

/// Every tampered record names the field it changed, and the fields cover the whole layout.
#[test]
fn s07_tampering_covers_every_field() {
    let (_, records) = records();
    let fields: std::collections::BTreeSet<&str> = records
        .iter()
        .filter_map(|record| record.input.get("tampered").and_then(Value::as_str))
        .collect();
    let every: std::collections::BTreeSet<&str> = [
        "magic",
        "version",
        "kdf",
        "memory",
        "iterations",
        "parallelism",
        "salt",
        "nonce",
        "payloadKind",
        "payloadLength",
        "ciphertext",
        "tag",
        "length",
    ]
    .into_iter()
    .collect();
    assert_eq!(fields, every);
}

/// The vectors' bounds are the crate's.
#[test]
fn s07_bounds_are_the_crates() {
    let (meta, _) = records();
    for (name, bounds) in [("standard", Bounds::STANDARD), ("test", Bounds::TEST)] {
        let recorded = &meta["bounds"][name];
        assert_eq!(params(&recorded["floor"]), bounds.floor(), "{name}");
        assert_eq!(params(&recorded["ceiling"]), bounds.ceiling(), "{name}");
        assert_eq!(
            recorded["maxWork"].as_u64(),
            Some(bounds.max_work()),
            "{name}"
        );
    }
}

/// The file is the one `vectors/sdk/MANIFEST.sha256` lists.
#[test]
fn s07_manifest() {
    use sha2::{Digest, Sha256};
    let manifest = include_str!("../../../vectors/sdk/MANIFEST.sha256");
    let line = manifest
        .lines()
        .find(|line| line.ends_with(&format!("  {CLASS}.jsonl")))
        .expect("the manifest lists the class");
    let digest = Sha256::digest(FILE.as_bytes());
    assert_eq!(
        line.split_once("  ").map(|(hash, _)| hash),
        Some(hex::encode(digest).as_str())
    );
}
