//! Account links: the S09 vectors (`vectors/sdk/S09-account-links.jsonl`, generated by
//! `tools/oracle/gen-link-vectors.js`, an implementation of the format independent of the SDK's),
//! and a test for every rule of `docs/account-links.md` with a case that fails if the rule is
//! dropped.

// Tests may panic on a broken vector or fixture: that is how they fail.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]

mod common;

use common::{Outcome, Record, Tally, VectorFile, compare, devnet_profile, run_class};
use heartwood_crypto::Aux;
use heartwood_crypto::utils::hex;
use iceroot_sdk_core::error::LinkProblem;
use iceroot_sdk_core::keys::Account;
use iceroot_sdk_core::link::{
    self, LinkExpected, LinkKind, LinkMessage, LinkRecord, LinkRequest, Recorded, RecordedEvent,
};
use iceroot_sdk_core::message;
use iceroot_sdk_core::profile::DevnetOptions;
use iceroot_sdk_core::{Error, ErrorCode, Profile, PublicKey};
use serde_json::{Value, json};

const HOLDER: &str = "this is a top secret passphrase";
const OTHER: &str = "another top secret passphrase";
const ID: u64 = 9_999_999_001;
/// 2026-09-26T12:34:56Z
const ISSUED: i64 = 1_790_426_096;
const NOW: i64 = ISSUED * 1000 + 1000;
const LATER: i64 = ISSUED + 86_400;
const LATER_NOW: i64 = LATER * 1000 + 1000;

fn profile() -> Profile {
    devnet_profile()
}

fn account(passphrase: &str) -> Account {
    Account::from_legacy_passphrase(&profile(), passphrase).unwrap()
}

fn text(value: &Value) -> &str {
    value.as_str().expect("a string")
}

fn reason_of<T: std::fmt::Debug>(result: Result<T, Error>) -> LinkProblem {
    match result {
        Err(Error::InvalidLink { problem }) => problem,
        other => panic!("{other:?}"),
    }
}

fn request(public_key: &PublicKey, issued_at: i64) -> LinkRequest<'_> {
    LinkRequest {
        github_id: ID,
        public_key,
        issued_at,
    }
}

fn link_text() -> String {
    link::build(&profile(), &request(account(HOLDER).public_key(), ISSUED)).unwrap()
}

fn revocation_text() -> String {
    link::build_revocation(
        &profile(),
        &request(account(HOLDER).public_key(), LATER),
        ISSUED,
    )
    .unwrap()
}

/// `text` with its line `index` (0-based) replaced by `line`.
fn with_line(text: &str, index: usize, line: &str) -> String {
    text.split('\n')
        .enumerate()
        .map(|(i, old)| if i == index { line } else { old })
        .collect::<Vec<_>>()
        .join("\n")
}

fn parse(text: &str, now: i64) -> Result<LinkMessage, Error> {
    link::parse(&profile(), text, &LinkExpected::default(), now)
}

// ------------------------------------------------------------------------------------------------
// The S09 vectors.

/// The fields of a checked message, in the JSON form of the vectors.
fn fields_json(fields: &LinkMessage) -> Value {
    let mut value = json!({
        "kind": fields.kind.as_str(),
        "network": fields.network,
        "githubId": fields.github_id,
        "account": fields.account,
        "publicKey": fields.public_key,
        "issuedAt": fields.issued_at,
        "issuedAtMs": fields.issued_at_ms,
    });
    if fields.kind == LinkKind::Revocation {
        value["endsLinkIssuedAt"] = json!(fields.ends_link_issued_at);
        value["endsLinkIssuedAtMs"] = json!(fields.ends_link_issued_at_ms);
    }
    value
}

fn expected_of(input: &Value) -> LinkExpected<'_> {
    let field = |key: &str| input["expected"].get(key);
    LinkExpected {
        kind: field("kind")
            .and_then(Value::as_str)
            .map(|kind| match kind {
                "link" => LinkKind::Link,
                "revocation" => LinkKind::Revocation,
                other => panic!("kind {other}"),
            }),
        github_id: field("githubId").and_then(Value::as_u64),
        public_key: field("publicKey").and_then(Value::as_str),
        address: field("address").and_then(Value::as_str),
    }
}

fn recorded_of(entry: &Value) -> Recorded {
    let at = entry["at"].as_i64().expect("a time");
    Recorded {
        network: text(&entry["network"]).to_owned(),
        github_id: entry["githubId"].as_u64().expect("an id"),
        account: text(&entry["account"]).to_owned(),
        event: match text(&entry["event"]) {
            "link" => RecordedEvent::Link { issued_at_ms: at },
            "revocation" => RecordedEvent::Revocation { issued_at_ms: at },
            "github-unlink" => RecordedEvent::GithubUnlink { posted_at_ms: at },
            other => panic!("event {other}"),
        },
    }
}

/// The outcome of `result` against the record: the same output, or the same error code and
/// details.
fn outcome(record: &Record, result: Result<Value, Error>) -> Outcome {
    match (&record.expected, result) {
        (Ok(expected), Ok(actual)) => compare(expected, &actual),
        (Err(expected), Err(error)) => compare(
            expected,
            &json!({ "class": error.code().as_str(), "details": error.details() }),
        ),
        (expected, actual) => Outcome::Failed(format!("expected {expected:?}, got {actual:?}")),
    }
}

fn run(record: &Record) -> Outcome {
    let input = &record.input;
    let now = || input["now"].as_i64().expect("a time");
    let aux = || Aux::fixed(hex::decode_array(text(&input["aux"])).expect("32 bytes"));
    let result = match record.op.as_str() {
        "link.build" => {
            let key = PublicKey::from_hex(text(&input["publicKey"])).expect("a key");
            let request = LinkRequest {
                github_id: input["githubId"].as_u64().expect("an id"),
                public_key: &key,
                issued_at: input["issuedAt"].as_i64().expect("a time"),
            };
            let built = match text(&input["kind"]) {
                "link" => link::build(&profile(), &request),
                _ => {
                    let ends = input["endsLinkIssuedAt"].as_i64().expect("a time");
                    link::build_revocation(&profile(), &request, ends)
                }
            };
            built.map(|message| json!({ "message": message }))
        }
        "link.parse" => link::parse(
            &profile(),
            text(&input["message"]),
            &expected_of(input),
            now(),
        )
        .map(|fields| fields_json(&fields)),
        "link.sign" => {
            let signer = account(text(&input["passphrase"]));
            let signed =
                link::sign_with(&profile(), &signer, text(&input["message"]), now(), aux());
            if let Ok(record) = &signed {
                // The record reads back from its JSON, and verifies.
                let again = LinkRecord::from_json(&record.to_json());
                let verified = link::verify(&profile(), record, &LinkExpected::default(), now());
                if again.as_ref() != Ok(record) || verified.is_err() {
                    return Outcome::Failed(format!("{again:?} {verified:?}"));
                }
            }
            signed.map(|record| {
                json!({
                    "record": {
                        "message": record.message,
                        "publicKey": record.public_key,
                        "signature": record.signature,
                        "algorithm": record.algorithm,
                        "network": record.network,
                    },
                    "json": record.to_json(),
                })
            })
        }
        "link.verify" => LinkRecord::from_json(text(&input["record"]))
            .and_then(|record| link::verify(&profile(), &record, &expected_of(input), now()))
            .map(|fields| fields_json(&fields)),
        "link.history" => {
            let recorded: Vec<Recorded> = input["recorded"]
                .as_array()
                .expect("a history")
                .iter()
                .map(recorded_of)
                .collect();
            parse(text(&input["message"]), now())
                .and_then(|fields| link::check_history(&fields, &recorded))
                .map(|()| json!({ "accepted": true }))
        }
        "message.sign" => message::sign_with(
            &profile(),
            &account(text(&input["passphrase"])),
            text(&input["message"]),
            aux(),
        )
        .map(|signed| json!({ "signature": signed.signature })),
        other => return Outcome::Failed(format!("unknown operation {other}")),
    };
    outcome(record, result)
}

#[test]
fn s09_account_links() {
    let file = VectorFile::load("sdk", "S09-account-links");
    assert_eq!(
        file.meta["network"]["name"].as_str(),
        Some(profile().message_network().unwrap().as_str())
    );
    assert_eq!(file.meta["algorithm"].as_str(), Some(message::ALGORITHM));
    let tally = run_class(&file, run);
    assert_eq!(
        tally,
        Tally {
            matched: 113,
            divergent: 0,
            skipped: 0
        }
    );
    // The vectors cover every refusal of the format.
    for reason in [
        "format",
        "field",
        "network",
        "github-id",
        "key",
        "address",
        "issued-at",
        "future",
        "ends-link",
        "mismatch",
        "json",
        "record",
        "signature",
        "replay",
        "unknown-link",
    ] {
        assert!(
            file.records.iter().any(|record| record
                .expected
                .as_ref()
                .is_err_and(|error| error["details"]["reason"] == reason)),
            "no vector refused for {reason}"
        );
    }
}

// ------------------------------------------------------------------------------------------------
// The format.

#[test]
fn build_writes_the_exact_bytes() {
    assert_eq!(
        link_text(),
        "IceRoot account link\nVersion: 1\nNetwork: heartwood-devnet-v90\n\
         GitHub user id: 9999999001\nAccount: dEHxjxZybRiykTqqZUgfQoMqZZ3RxVj1dt\n\
         Public key: 034151a3ec46b5670a682b0a63394f863587d1bc97483b1b6c70eb58e7f0aed192\n\
         Issued at: 2026-09-26T12:34:56Z\n\
         Intent: Link this GitHub account and this IceRoot account as the same holder.\n\
         No transaction or transfer is authorized."
    );
    assert_eq!(
        revocation_text(),
        "IceRoot account link revocation\nVersion: 1\nNetwork: heartwood-devnet-v90\n\
         GitHub user id: 9999999001\nAccount: dEHxjxZybRiykTqqZUgfQoMqZZ3RxVj1dt\n\
         Public key: 034151a3ec46b5670a682b0a63394f863587d1bc97483b1b6c70eb58e7f0aed192\n\
         Issued at: 2026-09-27T12:34:56Z\nEnds link issued at: 2026-09-26T12:34:56Z\n\
         Intent: End the link between this GitHub account and this IceRoot account.\n\
         No transaction or transfer is authorized."
    );
    let fields = parse(&revocation_text(), LATER_NOW).unwrap();
    assert_eq!(fields.kind, LinkKind::Revocation);
    assert_eq!(fields.github_id, ID);
    assert_eq!(fields.issued_at_ms, LATER * 1000);
    assert_eq!(fields.ends_link_issued_at_ms, Some(ISSUED * 1000));
    assert_eq!(
        fields.ends_link_issued_at.as_deref(),
        Some("2026-09-26T12:34:56Z")
    );
}

#[test]
fn build_refusals() {
    let holder = account(HOLDER);
    let key = holder.public_key();
    let refused = |github_id| {
        reason_of(link::build(
            &profile(),
            &LinkRequest {
                github_id,
                ..request(key, ISSUED)
            },
        ))
    };
    assert_eq!(refused(0), LinkProblem::GithubId);
    assert_eq!(refused(link::MAX_GITHUB_ID + 1), LinkProblem::GithubId);
    assert!(
        link::build(
            &profile(),
            &LinkRequest {
                github_id: link::MAX_GITHUB_ID,
                ..request(key, ISSUED)
            }
        )
        .is_ok()
    );
    assert_eq!(
        reason_of(link::build_revocation(
            &profile(),
            &request(key, ISSUED),
            ISSUED
        )),
        LinkProblem::EndsLink
    );
    assert_eq!(
        reason_of(link::build(&profile(), &request(key, 253_402_300_800))),
        LinkProblem::IssuedAt
    );
    // A profile without message signing has no link messages.
    let pq = Profile::devnet_pq(DevnetOptions::default());
    assert_eq!(
        link::build(&pq, &request(key, ISSUED)).unwrap_err().code(),
        ErrorCode::UnsupportedOnNetwork
    );
}

/// Every refusal of `parse`, with its reason; each case fails if its rule is dropped.
#[test]
fn parse_refusals() {
    let link = link_text();
    let revocation = revocation_text();
    let other = account(OTHER);
    let cases: Vec<(String, i64, LinkProblem)> = vec![
        // Exact bytes: no newline at the end, LF only, no extra line, no space around lines.
        (format!("{link}\n"), NOW, LinkProblem::Format),
        (link.replace('\n', "\r\n"), NOW, LinkProblem::Format),
        (format!("{link}\r"), NOW, LinkProblem::Format),
        (format!(" {link}"), NOW, LinkProblem::Format),
        (format!("{link}\nmore"), NOW, LinkProblem::Format),
        (
            with_line(&link, 0, "IceRoot account Link"),
            NOW,
            LinkProblem::Format,
        ),
        (with_line(&link, 1, "Version: 1 "), NOW, LinkProblem::Format),
        (with_line(&link, 7, "Intent: x"), NOW, LinkProblem::Format),
        (
            with_line(&link, 8, "No transfer."),
            NOW,
            LinkProblem::Format,
        ),
        (
            with_line(&link, 7, link::REVOCATION_INTENT_LINE),
            NOW,
            LinkProblem::Format,
        ),
        (
            with_line(&revocation, 8, link::INTENT_LINE),
            LATER_NOW,
            LinkProblem::Format,
        ),
        (
            link.replacen("IceRoot", "Ic\u{435}Root", 1),
            NOW,
            LinkProblem::Format,
        ),
        (
            "0123456789abcdef0123456789abcdef".to_owned(),
            NOW,
            LinkProblem::Format,
        ),
        (
            format!("{link}{}", " ".repeat(link::MAX_LENGTH)),
            NOW,
            LinkProblem::Format,
        ),
        // Labels and spaces.
        (
            with_line(&link, 2, "Network:heartwood-devnet-v90"),
            NOW,
            LinkProblem::Field,
        ),
        (
            with_line(&link, 4, "Account:  dEHxjxZybRiykTqqZUgfQoMqZZ3RxVj1dt"),
            NOW,
            LinkProblem::Field,
        ),
        (
            with_line(&link, 3, "GitHub user id: 9999999001\t"),
            NOW,
            LinkProblem::Field,
        ),
        (
            with_line(&link, 3, "GitHub user id: "),
            NOW,
            LinkProblem::Field,
        ),
        // The network, the id, the key and its address.
        (
            with_line(&link, 2, "Network: heartwood-devnet-v91"),
            NOW,
            LinkProblem::Network,
        ),
        (
            with_line(&link, 3, "GitHub user id: 09999999001"),
            NOW,
            LinkProblem::GithubId,
        ),
        (
            with_line(&link, 3, "GitHub user id: 0"),
            NOW,
            LinkProblem::GithubId,
        ),
        (
            with_line(&link, 3, "GitHub user id: 9007199254740992"),
            NOW,
            LinkProblem::GithubId,
        ),
        (
            with_line(&link, 3, "GitHub user id: 18446744073709551616"),
            NOW,
            LinkProblem::GithubId,
        ),
        (
            with_line(&link, 3, "GitHub user id: -1"),
            NOW,
            LinkProblem::GithubId,
        ),
        (
            with_line(
                &link,
                5,
                &format!(
                    "Public key: {}",
                    account(HOLDER).public_key().to_hex().to_uppercase()
                ),
            ),
            NOW,
            LinkProblem::Key,
        ),
        (
            with_line(&link, 5, &format!("Public key: 02{}", "ff".repeat(32))),
            NOW,
            LinkProblem::Key,
        ),
        (
            with_line(
                &link,
                5,
                &format!("Public key: {}", other.public_key().to_hex()),
            ),
            NOW,
            LinkProblem::Address,
        ),
        (
            with_line(&link, 4, &format!("Account: {}", other.address())),
            NOW,
            LinkProblem::Address,
        ),
        // Times.
        (
            with_line(&link, 6, "Issued at: 2026-09-26T12:34:56.000Z"),
            NOW,
            LinkProblem::IssuedAt,
        ),
        (
            with_line(&link, 6, "Issued at: 2026-02-29T12:34:56Z"),
            NOW,
            LinkProblem::IssuedAt,
        ),
        (link.clone(), ISSUED * 1000 - 30_001, LinkProblem::Future),
        (
            with_line(&revocation, 7, "Ends link issued at: 2026-09-27T12:34:56Z"),
            LATER_NOW,
            LinkProblem::EndsLink,
        ),
        (
            with_line(&revocation, 7, "Ends link issued at: 2026-09-28T12:34:56Z"),
            LATER_NOW,
            LinkProblem::EndsLink,
        ),
        (
            with_line(&revocation, 7, "Ends link issued at: yesterday"),
            LATER_NOW,
            LinkProblem::EndsLink,
        ),
    ];
    for (text, now, reason) in &cases {
        assert_eq!(reason_of(parse(text, *now)), *reason, "{text:?}");
    }
    // The bounds that pass: 30 seconds ahead, any age, the largest id.
    assert!(parse(&link, ISSUED * 1000 - 30_000).is_ok());
    assert!(parse(&link, NOW + 10 * 365 * 86_400_000).is_ok());
    let largest = with_line(&link, 3, "GitHub user id: 9007199254740991");
    assert_eq!(parse(&largest, NOW).unwrap().github_id, link::MAX_GITHUB_ID);
    // The network is the reader's profile's.
    let other_network = profile().with_network_byte(91);
    assert_eq!(
        reason_of(link::parse(
            &other_network,
            &link,
            &LinkExpected::default(),
            NOW
        )),
        LinkProblem::Network
    );
}

#[test]
fn parse_compares_what_the_reader_expects() {
    let link = link_text();
    let holder = account(HOLDER);
    let key = holder.public_key().to_hex();
    let address = holder.address().to_string();
    let all = LinkExpected {
        kind: Some(LinkKind::Link),
        github_id: Some(ID),
        public_key: Some(&key),
        address: Some(&address),
    };
    assert!(link::parse(&profile(), &link, &all, NOW).is_ok());
    for expected in [
        LinkExpected {
            kind: Some(LinkKind::Revocation),
            ..all
        },
        LinkExpected {
            github_id: Some(ID + 1),
            ..all
        },
        LinkExpected {
            public_key: Some("02cf05d38330aeddf8f5a668111881167458f86e325077c4911b0037cacc58c1a0"),
            ..all
        },
        LinkExpected {
            address: Some("dDSccdbPRhfrcbUeFLMbGC1rtnfCsjJcNF"),
            ..all
        },
    ] {
        assert_eq!(
            reason_of(link::parse(&profile(), &link, &expected, NOW)),
            LinkProblem::Mismatch
        );
    }
}

// ------------------------------------------------------------------------------------------------
// Signing, the record and verification.

#[test]
fn sign_then_verify() {
    let holder = account(HOLDER);
    for (text, now) in [(link_text(), NOW), (revocation_text(), LATER_NOW)] {
        let record = link::sign(&profile(), &holder, &text, now).unwrap();
        assert_eq!(record.message, text);
        assert_eq!(record.public_key, holder.public_key().to_hex());
        assert_eq!(record.algorithm, "secp256k1-bip340-sha256");
        assert_eq!(record.network, "heartwood-devnet-v90");
        let fields = link::verify(&profile(), &record, &LinkExpected::default(), now).unwrap();
        assert_eq!(fields, parse(&text, now).unwrap());
        let again = LinkRecord::from_json(&record.to_json()).unwrap();
        assert_eq!(again, record);
        // A plain message signature check agrees.
        assert!(message::verify(&text, &record.message_signature()));
    }
}

#[test]
fn sign_checks_the_message_against_the_account_and_the_time_first() {
    let holder = account(HOLDER);
    let other = account(OTHER);
    let link = link_text();
    assert_eq!(
        reason_of(link::sign(&profile(), &other, &link, NOW)),
        LinkProblem::Mismatch
    );
    assert_eq!(
        reason_of(link::sign(
            &profile(),
            &holder,
            &link,
            ISSUED * 1000 - 31_000
        )),
        LinkProblem::Future
    );
    assert_eq!(
        reason_of(link::sign(&profile(), &holder, "hello", NOW)),
        LinkProblem::Format
    );
    // A message for another network than the signer's is refused, and a profile without message
    // signing signs nothing.
    let other_network = profile().with_network_byte(91);
    assert_eq!(
        reason_of(link::sign(&other_network, &holder, &link, NOW)),
        LinkProblem::Network
    );
    let pq = Profile::devnet_pq(DevnetOptions::default());
    assert_eq!(
        link::sign(&pq, &holder, &link, NOW).unwrap_err().code(),
        ErrorCode::UnsupportedOnNetwork
    );
}

#[test]
fn verify_refusals() {
    let holder = account(HOLDER);
    let other = account(OTHER);
    let link = link_text();
    let signed = link::sign_with(&profile(), &holder, &link, NOW, Aux::fixed([0x42; 32])).unwrap();
    let check = |record: &LinkRecord| {
        reason_of(link::verify(
            &profile(),
            record,
            &LinkExpected::default(),
            NOW,
        ))
    };
    let altered = with_line(&link, 3, "GitHub user id: 9999999002");
    let by_other = message::sign(&profile(), &other, "x").unwrap();
    let cases = [
        (
            LinkRecord {
                message: altered.clone(),
                ..signed.clone()
            },
            LinkProblem::Signature,
        ),
        (
            LinkRecord {
                public_key: by_other.public_key.clone(),
                ..signed.clone()
            },
            LinkProblem::Record,
        ),
        (
            LinkRecord {
                network: "heartwood-devnet-v91".to_owned(),
                ..signed.clone()
            },
            LinkProblem::Record,
        ),
        (
            LinkRecord {
                algorithm: "ml-dsa-65".to_owned(),
                ..signed.clone()
            },
            LinkProblem::Record,
        ),
        (
            LinkRecord {
                signature: signed.signature.to_uppercase(),
                ..signed.clone()
            },
            LinkProblem::Signature,
        ),
        (
            LinkRecord {
                signature: by_other.signature.clone(),
                ..signed.clone()
            },
            LinkProblem::Signature,
        ),
        (
            LinkRecord {
                signature: format!("{}00", signed.signature),
                ..signed.clone()
            },
            LinkProblem::Signature,
        ),
    ];
    for (record, reason) in &cases {
        assert_eq!(check(record), *reason, "{record:?}");
    }
    // The expected identity is compared too.
    assert_eq!(
        reason_of(link::verify(
            &profile(),
            &signed,
            &LinkExpected {
                github_id: Some(ID + 1),
                ..LinkExpected::default()
            },
            NOW
        )),
        LinkProblem::Mismatch
    );
    // The 32-byte text is never a link, signed as a message hashes first and the record fails on
    // its format before any signature check.
    let short = "0123456789abcdef0123456789abcdef";
    let short_signed = message::sign(&profile(), &holder, short).unwrap();
    assert!(message::verify(short, &short_signed));
    assert_eq!(
        check(&LinkRecord::from_signature(short, short_signed)),
        LinkProblem::Format
    );
}

#[test]
fn the_record_json_is_fixed() {
    let record = LinkRecord {
        message: "a\nb\"c\\d\u{1}\u{1f}\u{7f}é\u{2028}/".to_owned(),
        public_key: "02".to_owned(),
        signature: "ab".to_owned(),
        algorithm: "secp256k1-bip340-sha256".to_owned(),
        network: "heartwood-devnet-v90".to_owned(),
    };
    // As JavaScript's JSON.stringify writes the same object: the members in this order, no
    // white space, the short escapes, \u00XX in lowercase for other controls, nothing else
    // escaped.
    assert_eq!(
        record.to_json(),
        "{\"message\":\"a\\nb\\\"c\\\\d\\u0001\\u001f\u{7f}é\u{2028}/\",\"publicKey\":\"02\",\
         \"signature\":\"ab\",\"algorithm\":\"secp256k1-bip340-sha256\",\
         \"network\":\"heartwood-devnet-v90\"}"
    );
    assert_eq!(LinkRecord::from_json(&record.to_json()).unwrap(), record);
    let json = |value: Value| reason_of(LinkRecord::from_json(&value.to_string()));
    let mut extra = serde_json::from_str::<Value>(&record.to_json()).unwrap();
    extra["comment"] = json!("x");
    assert_eq!(json(extra), LinkProblem::Json);
    let mut missing = serde_json::from_str::<Value>(&record.to_json()).unwrap();
    missing.as_object_mut().unwrap().remove("network");
    assert_eq!(json(missing), LinkProblem::Json);
    let mut number = serde_json::from_str::<Value>(&record.to_json()).unwrap();
    number["network"] = json!(90);
    assert_eq!(json(number), LinkProblem::Json);
    assert_eq!(json(json!([1])), LinkProblem::Json);
    assert_eq!(reason_of(LinkRecord::from_json("{")), LinkProblem::Json);
    let long = format!("{{\"message\":\"{}\"}}", "x".repeat(link::MAX_JSON_LENGTH));
    assert_eq!(reason_of(LinkRecord::from_json(&long)), LinkProblem::Json);
}

#[test]
fn a_doubled_member_is_refused() {
    let signed = link::sign(&profile(), &account(HOLDER), &link_text(), NOW).unwrap();
    let json = signed.to_json();
    // A reader that kept the last of two members would verify a message other than the one a
    // person reading the record sees first.
    for doubled in [
        json.replacen("{\"message\":", "{\"message\":\"decoy\",\"message\":", 1),
        json.replacen(
            "{\"message\":",
            "{\"message\":{\"a\":[1,{\"b\":2}]},\"message\":",
            1,
        ),
        json.replacen("\"network\":", "\"network\":\"x\",\"network\":", 1),
        json.replacen(
            "{\"message\":",
            "{ \"message\" : \"decoy\" , \"message\":",
            1,
        ),
        json.replacen(
            "\"signature\":",
            "\"sign\\u0061ture\":\"00\",\"signature\":",
            1,
        ),
    ] {
        assert_eq!(
            reason_of(LinkRecord::from_json(&doubled)),
            LinkProblem::Json,
            "{doubled}"
        );
    }
    // Text that only looks like a member inside a value is no member.
    let mut quoted = signed.clone();
    quoted.message = "{\"message\":\"x\",\"message\":\"y\"}: \\".to_owned();
    assert_eq!(LinkRecord::from_json(&quoted.to_json()).unwrap(), quoted);
    let spaced = format!(" {} ", json.replace(",\"", " , \"").replace("\":", "\" : "));
    assert_eq!(LinkRecord::from_json(&spaced).unwrap(), signed);
}

#[test]
fn the_error_has_a_stable_code_and_reason() {
    let error = Error::InvalidLink {
        problem: LinkProblem::UnknownLink,
    };
    assert_eq!(error.code(), ErrorCode::InvalidLink);
    assert_eq!(error.code().as_str(), "InvalidLink");
    assert_eq!(
        error.code().group(),
        iceroot_sdk_core::error::ErrorGroup::Input
    );
    assert_eq!(error.details(), json!({ "reason": "unknown-link" }));
    assert_eq!(
        error.to_string(),
        "invalid account link: the revocation names no recorded link"
    );
}

// ------------------------------------------------------------------------------------------------
// The no-replay rule.

fn entry(event: RecordedEvent) -> Recorded {
    Recorded {
        network: "heartwood-devnet-v90".to_owned(),
        github_id: ID,
        account: "dEHxjxZybRiykTqqZUgfQoMqZZ3RxVj1dt".to_owned(),
        event,
    }
}

#[test]
fn the_no_replay_rule() {
    let link = parse(&link_text(), NOW).unwrap();
    let revocation = parse(&revocation_text(), LATER_NOW).unwrap();
    let linked = entry(RecordedEvent::Link {
        issued_at_ms: ISSUED * 1000,
    });
    let check = link::check_history;
    assert_eq!(check(&link, &[]), Ok(()));
    // The same link posted again, and a link older than a revocation or an unlink.
    assert_eq!(
        reason_of(check(&link, std::slice::from_ref(&linked))),
        LinkProblem::Replay
    );
    for event in [
        RecordedEvent::Revocation {
            issued_at_ms: LATER * 1000,
        },
        RecordedEvent::GithubUnlink {
            posted_at_ms: ISSUED * 1000 + 1,
        },
    ] {
        assert_eq!(
            reason_of(check(&link, &[entry(event)])),
            LinkProblem::Replay
        );
    }
    // An unlink just before the link does not block it.
    let before = entry(RecordedEvent::GithubUnlink {
        posted_at_ms: ISSUED * 1000 - 1,
    });
    assert_eq!(check(&link, &[before]), Ok(()));
    // A revocation of a recorded link; of none; and one older than a later link.
    assert_eq!(check(&revocation, std::slice::from_ref(&linked)), Ok(()));
    assert_eq!(reason_of(check(&revocation, &[])), LinkProblem::UnknownLink);
    let off_by_a_second = entry(RecordedEvent::Link {
        issued_at_ms: ISSUED * 1000 - 1000,
    });
    assert_eq!(
        reason_of(check(&revocation, &[off_by_a_second])),
        LinkProblem::UnknownLink
    );
    // A revocation naming a time that only a revocation or an unlink has is no link.
    for event in [
        RecordedEvent::Revocation {
            issued_at_ms: ISSUED * 1000,
        },
        RecordedEvent::GithubUnlink {
            posted_at_ms: ISSUED * 1000,
        },
    ] {
        assert_eq!(
            reason_of(check(&revocation, &[entry(event)])),
            LinkProblem::UnknownLink
        );
    }
    let later_link = entry(RecordedEvent::Link {
        issued_at_ms: LATER * 1000 + 60_000,
    });
    assert_eq!(
        reason_of(check(&revocation, &[linked.clone(), later_link])),
        LinkProblem::Replay
    );
    // Only the same GitHub id, account and network count.
    let later = RecordedEvent::Revocation {
        issued_at_ms: LATER * 1000,
    };
    let others = [
        Recorded {
            github_id: ID + 1,
            ..entry(later)
        },
        Recorded {
            account: "dDSccdbPRhfrcbUeFLMbGC1rtnfCsjJcNF".to_owned(),
            ..entry(later)
        },
        Recorded {
            network: "heartwood-devnet-v91".to_owned(),
            ..entry(later)
        },
    ];
    assert_eq!(check(&link, &others), Ok(()));
    let foreign_link = others.clone().map(|other| Recorded {
        event: linked.event,
        ..other
    });
    assert_eq!(
        reason_of(check(&revocation, &foreign_link)),
        LinkProblem::UnknownLink
    );
    // A checked message gives its own history entry.
    assert_eq!(Recorded::of(&link), linked);
    assert_eq!(
        Recorded::of(&revocation).event,
        RecordedEvent::Revocation {
            issued_at_ms: LATER * 1000
        }
    );
    assert_eq!(later.time_ms(), LATER * 1000);
}

// ------------------------------------------------------------------------------------------------
// Plain message signing.

#[test]
fn plain_signing_refuses_link_and_revocation_text() {
    let holder = account(HOLDER);
    let refused = Error::InvalidArgument {
        reason: "an account link is signed only as a checked link, never as a plain message",
    };
    let link = link_text();
    let revocation = revocation_text();
    for text in [
        link.clone(),
        revocation.clone(),
        link::TITLE.to_owned(),
        link::REVOCATION_TITLE.to_owned(),
        format!("{link}\n"),
        with_line(&link, 2, "Network: heartwood-devnet-v91"),
        format!("{}\nanything", link::TITLE),
    ] {
        for result in [
            message::sign(&profile(), &holder, &text),
            message::sign_with(&profile(), &holder, &text, Aux::fixed([0x42; 32])),
            message::sign_bytes(&profile(), &holder, text.as_bytes()),
            message::sign_bytes_with(&profile(), &holder, text.as_bytes(), Aux::fixed([0x42; 32])),
        ] {
            assert_eq!(result.unwrap_err(), refused, "{text:?}");
        }
    }
    // Text whose first line is not exactly a link's is a message, and its signature is no
    // link's.
    for text in [
        format!(" {link}"),
        format!("\n{link}"),
        link.replace('\n', "\r\n"),
        format!("Quoted: {}", link::TITLE),
        format!("{}s", link::TITLE),
    ] {
        let signed = message::sign(&profile(), &holder, &text).unwrap();
        assert!(message::verify(&text, &signed));
        assert!(!message::verify(&link, &signed));
    }
}
