//! The SDK's own vectors (`vectors/sdk/`, generated by `tools/oracle/gen-sdk-vectors.js` with the
//! reference implementation's libraries as the oracle) run through the SDK's public API:
//! phrases, hardened derivation, message signatures and sign-in messages.

mod common;

use common::{
    Outcome, Record, Tally, VectorFile, check_manifest, compare, devnet_profile, run_class,
    vectors_dir,
};
use heartwood_crypto::Aux;
use heartwood_crypto::utils::hex;
use iceroot_sdk_core::derivation;
use iceroot_sdk_core::error::{PhraseProblem, SignInProblem};
use iceroot_sdk_core::keys::{Account, AccountOptions, KeyOrigin};
use iceroot_sdk_core::message::{self, MessageSignature};
use iceroot_sdk_core::phrase::{Mnemonic, bip39};
use iceroot_sdk_core::signin::{self, SignInExpected};
use iceroot_sdk_core::{Error, Profile};
use serde_json::{Value, json};

fn load(class: &str) -> VectorFile {
    VectorFile::load("sdk", class)
}

fn text(value: &Value) -> &str {
    value.as_str().expect("a string")
}

fn profile() -> Profile {
    devnet_profile()
}

fn output(record: &Record) -> &Value {
    record.expected.as_ref().expect("an output")
}

#[test]
fn manifest() {
    check_manifest(&vectors_dir().join("sdk"));
}

#[test]
fn s01_phrases() {
    let file = load("S01-phrases");
    let tally = run_class(&file, |record| {
        let input = &record.input;
        match record.op.as_str() {
            "bip39.published" => {
                let entropy = hex::decode(text(&input["entropy"])).expect("hex");
                let mnemonic = bip39::entropy_to_mnemonic(&entropy).expect("a mnemonic");
                let seed =
                    bip39::mnemonic_to_seed(&mnemonic, text(&input["passphrase"])).expect("a seed");
                let master = derivation::public_key_at(seed.as_bytes(), &[]).expect("a key");
                // Phrases keys are made from give the same seed through a Mnemonic.
                if entropy.len() >= 24 {
                    let phrase = Mnemonic::from_entropy(&entropy).expect("a phrase");
                    let again = phrase.seed(text(&input["passphrase"])).expect("a seed");
                    if again.as_bytes() != seed.as_bytes() {
                        return Outcome::Failed("the Mnemonic's seed differs".into());
                    }
                }
                compare(
                    output(record),
                    &json!({
                        "mnemonic": mnemonic.as_str(),
                        "seed": hex::encode(seed.as_bytes()),
                        "masterPublicKey": master.to_hex(),
                    }),
                )
            }
            "bip39.mnemonicToSeed" => {
                let phrase = Mnemonic::parse(text(&input["mnemonic"])).expect("a phrase");
                let seed = phrase.seed(text(&input["passphrase"])).expect("a seed");
                compare(
                    output(record),
                    &json!({ "seed": hex::encode(seed.as_bytes()) }),
                )
            }
            "bip39.validate" => {
                let mnemonic = text(&input["mnemonic"]);
                let expected = output(record);
                let valid = expected["valid"].as_bool().expect("a verdict");
                let words = expected["words"].as_u64().expect("a count") as usize;
                let entropy = bip39::mnemonic_to_entropy(mnemonic);
                let mut actual = json!({ "valid": entropy.is_ok(), "words": words });
                if let Ok(entropy) = &entropy {
                    actual["entropy"] = json!(hex::encode(entropy));
                }
                // The phrase for keys: 18 words or more, else PhraseTooShort.
                let parsed = Mnemonic::parse(mnemonic);
                let check = Mnemonic::check(mnemonic);
                let consistent = match (valid, words >= 18, &parsed) {
                    (true, true, Ok(phrase)) => phrase.word_count() == words && check.is_ok(),
                    (true, false, Err(Error::PhraseTooShort { words: short, .. })) => {
                        *short == words && check.problem == Some(PhraseProblem::TooShort { words })
                    }
                    (false, _, Err(Error::InvalidPhrase { problem })) => {
                        check.problem == Some(*problem)
                    }
                    _ => false,
                };
                if !consistent {
                    return Outcome::Failed(format!("Mnemonic::parse gives {parsed:?}"));
                }
                compare(expected, &actual)
            }
            "genesis.passphrase" => {
                let passphrase = text(&input["passphrase"]);
                let account =
                    Account::from_legacy_passphrase(&profile(), passphrase).expect("a key");
                let words = passphrase.split(' ').count();
                if !matches!(
                    Mnemonic::parse(passphrase),
                    Err(Error::PhraseTooShort { .. })
                ) {
                    return Outcome::Failed("a 12-word phrase makes no key".into());
                }
                compare(
                    output(record),
                    &json!({
                        "valid": bip39::mnemonic_to_entropy(passphrase).is_ok(),
                        "words": words,
                        "publicKey": account.public_key().to_hex(),
                        "address": account.address().to_string(),
                    }),
                )
            }
            other => Outcome::Failed(format!("unknown operation {other}")),
        }
    });
    assert_eq!(
        tally,
        Tally {
            matched: 90,
            divergent: 0,
            skipped: 0
        }
    );
}

#[test]
fn s02_derivation() {
    let file = load("S02-derivation");
    let tally = run_class(&file, |record| {
        let input = &record.input;
        match record.op.as_str() {
            // The chain code is not part of the SDK's API; the child keys of a child check it.
            "bip32.hardened" => {
                let seed = hex::decode(text(&input["seed"])).expect("hex");
                let steps: Vec<u32> = input["steps"]
                    .as_array()
                    .expect("steps")
                    .iter()
                    .map(|step| u32::try_from(step.as_u64().expect("a step")).expect("u32"))
                    .collect();
                let key = derivation::public_key_at(&seed, &steps).expect("a key");
                compare(&output(record)["publicKey"], &json!(key.to_hex()))
            }
            "wallet.derive" => {
                assert_eq!(input["coinType"], json!(profile().coin_type()));
                let options = AccountOptions {
                    account: u32::try_from(input["account"].as_u64().expect("an account"))
                        .expect("u32"),
                    index: u32::try_from(input["index"].as_u64().expect("an index")).expect("u32"),
                    passphrase: text(&input["passphrase"]),
                };
                let account = Mnemonic::parse(text(&input["mnemonic"]))
                    .and_then(|phrase| Account::from_phrase(&profile(), &phrase, &options));
                match (&record.expected, account) {
                    (Ok(expected), Ok(account)) => {
                        let KeyOrigin::Phrase(path) = account.origin() else {
                            return Outcome::Failed("not a phrase account".into());
                        };
                        compare(
                            expected,
                            &json!({
                                "path": path.to_string(),
                                "publicKey": account.public_key().to_hex(),
                                "address": account.address().to_string(),
                            }),
                        )
                    }
                    (Err(error), Err(ours)) => {
                        compare(&error["class"], &json!(ours.code().as_str()))
                    }
                    (expected, actual) => Outcome::Failed(format!(
                        "expected {expected:?}, got {:?}",
                        actual.map(|account| account.address().to_string())
                    )),
                }
            }
            other => Outcome::Failed(format!("unknown operation {other}")),
        }
    });
    assert_eq!(
        tally,
        Tally {
            matched: 65,
            divergent: 0,
            skipped: 0
        }
    );
}

#[test]
fn s03_messages() {
    let file = load("S03-messages");
    let tally = run_class(&file, |record| {
        let input = &record.input;
        match record.op.as_str() {
            "message.sign" => {
                let account =
                    Account::from_legacy_passphrase(&profile(), text(&input["passphrase"]))
                        .expect("a key");
                let aux = Aux::fixed(hex::decode_array(text(&input["aux"])).expect("32 bytes"));
                let signed = message::sign_with(&profile(), &account, text(&input["message"]), aux)
                    .expect("a signature");
                if !message::verify(text(&input["message"]), &signed) {
                    return Outcome::Failed("the SDK's own signature does not verify".into());
                }
                compare(
                    output(record),
                    &json!({
                        "publicKey": signed.public_key,
                        "address": account.address().to_string(),
                        "signature": signed.signature,
                    }),
                )
            }
            "message.verify" => {
                let signature = MessageSignature {
                    public_key: text(&input["publicKey"]).to_owned(),
                    signature: text(&input["signature"]).to_owned(),
                    algorithm: message::ALGORITHM.to_owned(),
                    network: profile().message_network().expect("a network"),
                };
                compare(
                    output(record),
                    &json!({ "valid": message::verify(text(&input["message"]), &signature) }),
                )
            }
            other => Outcome::Failed(format!("unknown operation {other}")),
        }
    });
    assert_eq!(
        tally,
        Tally {
            matched: 40,
            divergent: 0,
            skipped: 0
        }
    );
}

#[test]
fn s04_signin() {
    let file = load("S04-signin");
    let tally = run_class(&file, |record| {
        let input = &record.input;
        let field = |key: &str| input["expected"].get(key).and_then(Value::as_str);
        let expected = SignInExpected {
            origin: field("origin"),
            public_key: field("publicKey"),
            address: field("address"),
        };
        let now = input["now"].as_i64().expect("a time");
        let parsed = signin::parse(&profile(), text(&input["message"]), &expected, now);
        match (&record.expected, parsed) {
            (Ok(fields), Ok(challenge)) => compare(
                &json!([
                    fields["origin"],
                    fields["uri"],
                    fields["network"],
                    fields["publicKey"],
                    fields["address"],
                    fields["nonce"],
                    fields["issuedAtMs"],
                    fields["expiresAtMs"],
                ]),
                &json!([
                    challenge.origin,
                    challenge.uri,
                    challenge.network,
                    challenge.public_key,
                    challenge.address,
                    challenge.nonce,
                    challenge.issued_at_ms,
                    challenge.expires_at_ms,
                ]),
            ),
            (
                Ok(_),
                Err(Error::InvalidSignIn {
                    problem: SignInProblem::Identity,
                }),
            ) if record.name.as_deref() == Some("another key's address") => Outcome::Divergent(
                "the wallet's check compares the address only with the identity it expects; the \
                 SDK also refuses an address that is not the key's",
            ),
            (Err(_), Err(Error::InvalidSignIn { .. })) => Outcome::Matched,
            (expected, actual) => Outcome::Failed(format!("expected {expected:?}, got {actual:?}")),
        }
    });
    assert_eq!(
        tally,
        Tally {
            matched: 34,
            divergent: 1,
            skipped: 0
        }
    );
}
