//! The SDK's own vectors (`vectors/sdk/`, generated by `tools/oracle/gen-sdk-vectors.js` with the
//! reference implementation's libraries as the oracle) run through the SDK's public API:
//! phrases, hardened derivation, message signatures, sign-in messages, transactions, fee floors
//! and ownership proofs.

// Tests may panic on a broken vector or fixture: that is how they fail.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]

mod common;

use common::{
    DEVNET, Outcome, Record, Tally, VectorFile, check_devnet, check_manifest, compare,
    devnet_profile, run_class, vectors_dir,
};
use heartwood_crypto::Aux;
use heartwood_crypto::utils::hex;
use iceroot_sdk_core::address::Address;
use iceroot_sdk_core::amount::Amount;
use iceroot_sdk_core::derivation;
use iceroot_sdk_core::error::{PhraseProblem, SignInProblem, VoteProblem};
use iceroot_sdk_core::fee::{FeeChoice, FeeSource};
use iceroot_sdk_core::keys::{Account, AccountOptions, KeyOrigin};
use iceroot_sdk_core::message::{self, MessageSignature};
use iceroot_sdk_core::ownership::{
    self, IceRootAccount, OwnershipProof, ProofExpected, ProofRequest, SolarKey,
};
use iceroot_sdk_core::phrase::{Mnemonic, bip39};
use iceroot_sdk_core::signin::{self, SignInExpected};
use iceroot_sdk_core::transaction::{
    Draft, DraftRequest, OnlineFacts, Operation, Recipient, Resignation, VoteEntry,
};
use iceroot_sdk_core::{Chain, Error, ErrorCode, Profile, PublicKey, PublicKeyBytes};
use serde_json::{Value, json};

fn load(class: &str) -> VectorFile {
    VectorFile::load("sdk", class)
}

fn text(value: &Value) -> &str {
    value.as_str().expect("a string")
}

fn profile() -> Profile {
    devnet_profile()
}

fn output(record: &Record) -> &Value {
    record.expected.as_ref().expect("an output")
}

#[test]
fn manifest() {
    check_manifest(&vectors_dir().join("sdk"));
}

#[test]
fn s01_phrases() {
    let file = load("S01-phrases");
    let tally = run_class(&file, |record| {
        let input = &record.input;
        match record.op.as_str() {
            "bip39.published" => {
                let entropy = hex::decode(text(&input["entropy"])).expect("hex");
                let mnemonic = bip39::entropy_to_mnemonic(&entropy).expect("a mnemonic");
                let seed =
                    bip39::mnemonic_to_seed(&mnemonic, text(&input["passphrase"])).expect("a seed");
                let master = derivation::public_key_at(seed.as_bytes(), &[]).expect("a key");
                // Phrases keys are made from give the same seed through a Mnemonic.
                if entropy.len() >= 24 {
                    let phrase = Mnemonic::from_entropy(&entropy).expect("a phrase");
                    let again = phrase.seed(text(&input["passphrase"])).expect("a seed");
                    if again.as_bytes() != seed.as_bytes() {
                        return Outcome::Failed("the Mnemonic's seed differs".into());
                    }
                    // The entropy a keystore stores, from the phrase made and the phrase read.
                    let parsed = Mnemonic::parse(&mnemonic).expect("a phrase");
                    if phrase.entropy() != entropy || parsed.entropy() != entropy {
                        return Outcome::Failed("the Mnemonic's entropy differs".into());
                    }
                }
                compare(
                    output(record),
                    &json!({
                        "mnemonic": mnemonic.as_str(),
                        "seed": hex::encode(seed.as_bytes()),
                        "masterPublicKey": master.to_hex(),
                    }),
                )
            }
            "bip39.mnemonicToSeed" => {
                let phrase = Mnemonic::parse(text(&input["mnemonic"])).expect("a phrase");
                let seed = phrase.seed(text(&input["passphrase"])).expect("a seed");
                compare(
                    output(record),
                    &json!({ "seed": hex::encode(seed.as_bytes()) }),
                )
            }
            "bip39.validate" => {
                let mnemonic = text(&input["mnemonic"]);
                let expected = output(record);
                let valid = expected["valid"].as_bool().expect("a verdict");
                let words = expected["words"].as_u64().expect("a count") as usize;
                let entropy = bip39::mnemonic_to_entropy(mnemonic);
                let mut actual = json!({ "valid": entropy.is_ok(), "words": words });
                if let Ok(entropy) = &entropy {
                    actual["entropy"] = json!(hex::encode(entropy));
                }
                // The phrase for keys: 18 words or more, else PhraseTooShort.
                let parsed = Mnemonic::parse(mnemonic);
                let check = Mnemonic::check(mnemonic);
                let consistent = match (valid, words >= 18, &parsed) {
                    (true, true, Ok(phrase)) => {
                        phrase.word_count() == words
                            && check.is_ok()
                            && entropy
                                .as_ref()
                                .is_ok_and(|e| e.as_slice() == phrase.entropy())
                    }
                    (true, false, Err(Error::PhraseTooShort { words: short, .. })) => {
                        *short == words && check.problem == Some(PhraseProblem::TooShort { words })
                    }
                    (false, _, Err(Error::InvalidPhrase { problem })) => {
                        check.problem == Some(*problem)
                    }
                    _ => false,
                };
                if !consistent {
                    return Outcome::Failed(format!("Mnemonic::parse gives {parsed:?}"));
                }
                compare(expected, &actual)
            }
            "genesis.passphrase" => {
                let passphrase = text(&input["passphrase"]);
                let account =
                    Account::from_legacy_passphrase(&profile(), passphrase).expect("a key");
                let words = passphrase.split(' ').count();
                if !matches!(
                    Mnemonic::parse(passphrase),
                    Err(Error::PhraseTooShort { .. })
                ) {
                    return Outcome::Failed("a 12-word phrase makes no key".into());
                }
                compare(
                    output(record),
                    &json!({
                        "valid": bip39::mnemonic_to_entropy(passphrase).is_ok(),
                        "words": words,
                        "publicKey": account.public_key().to_hex(),
                        "address": account.address().to_string(),
                    }),
                )
            }
            other => Outcome::Failed(format!("unknown operation {other}")),
        }
    });
    assert_eq!(
        tally,
        Tally {
            matched: 90,
            divergent: 0,
            skipped: 0
        }
    );
}

#[test]
fn s02_derivation() {
    let file = load("S02-derivation");
    let tally = run_class(&file, |record| {
        let input = &record.input;
        match record.op.as_str() {
            // The chain code is not part of the SDK's API; the child keys of a child check it.
            "bip32.hardened" => {
                let seed = hex::decode(text(&input["seed"])).expect("hex");
                let steps: Vec<u32> = input["steps"]
                    .as_array()
                    .expect("steps")
                    .iter()
                    .map(|step| u32::try_from(step.as_u64().expect("a step")).expect("u32"))
                    .collect();
                let key = derivation::public_key_at(&seed, &steps).expect("a key");
                compare(&output(record)["publicKey"], &json!(key.to_hex()))
            }
            "wallet.derive" => {
                assert_eq!(input["coinType"], json!(profile().coin_type()));
                let options = AccountOptions {
                    account: u32::try_from(input["account"].as_u64().expect("an account"))
                        .expect("u32"),
                    index: u32::try_from(input["index"].as_u64().expect("an index")).expect("u32"),
                    passphrase: text(&input["passphrase"]),
                };
                let account = Mnemonic::parse(text(&input["mnemonic"]))
                    .and_then(|phrase| Account::from_phrase(&profile(), &phrase, &options));
                match (&record.expected, account) {
                    (Ok(expected), Ok(account)) => {
                        let KeyOrigin::Phrase(path) = account.origin() else {
                            return Outcome::Failed("not a phrase account".into());
                        };
                        compare(
                            expected,
                            &json!({
                                "path": path.to_string(),
                                "publicKey": account.public_key().to_hex(),
                                "address": account.address().to_string(),
                            }),
                        )
                    }
                    (Err(error), Err(ours)) => {
                        compare(&error["class"], &json!(ours.code().as_str()))
                    }
                    (expected, actual) => Outcome::Failed(format!(
                        "expected {expected:?}, got {:?}",
                        actual.map(|account| account.address().to_string())
                    )),
                }
            }
            other => Outcome::Failed(format!("unknown operation {other}")),
        }
    });
    assert_eq!(
        tally,
        Tally {
            matched: 65,
            divergent: 0,
            skipped: 0
        }
    );
}

#[test]
fn s03_messages() {
    let file = load("S03-messages");
    let tally = run_class(&file, |record| {
        let input = &record.input;
        match record.op.as_str() {
            "message.sign" => {
                let account =
                    Account::from_legacy_passphrase(&profile(), text(&input["passphrase"]))
                        .expect("a key");
                let aux = Aux::fixed(hex::decode_array(text(&input["aux"])).expect("32 bytes"));
                let signed = message::sign_with(&profile(), &account, text(&input["message"]), aux)
                    .expect("a signature");
                if !message::verify(text(&input["message"]), &signed) {
                    return Outcome::Failed("the SDK's own signature does not verify".into());
                }
                compare(
                    output(record),
                    &json!({
                        "publicKey": signed.public_key,
                        "address": account.address().to_string(),
                        "signature": signed.signature,
                    }),
                )
            }
            "message.verify" => {
                let signature = MessageSignature {
                    public_key: text(&input["publicKey"]).to_owned(),
                    signature: text(&input["signature"]).to_owned(),
                    algorithm: message::ALGORITHM.to_owned(),
                    network: profile().message_network().expect("a network"),
                };
                compare(
                    output(record),
                    &json!({ "valid": message::verify(text(&input["message"]), &signature) }),
                )
            }
            other => Outcome::Failed(format!("unknown operation {other}")),
        }
    });
    assert_eq!(
        tally,
        Tally {
            matched: 40,
            divergent: 0,
            skipped: 0
        }
    );
}

#[test]
fn s04_signin() {
    let file = load("S04-signin");
    let tally = run_class(&file, |record| {
        let input = &record.input;
        let field = |key: &str| input["expected"].get(key).and_then(Value::as_str);
        let expected = SignInExpected {
            origin: field("origin"),
            public_key: field("publicKey"),
            address: field("address"),
        };
        let now = input["now"].as_i64().expect("a time");
        let parsed = signin::parse(&profile(), text(&input["message"]), &expected, now);
        match (&record.expected, parsed) {
            (Ok(fields), Ok(challenge)) => compare(
                &json!([
                    fields["origin"],
                    fields["uri"],
                    fields["network"],
                    fields["publicKey"],
                    fields["address"],
                    fields["nonce"],
                    fields["issuedAtMs"],
                    fields["expiresAtMs"],
                ]),
                &json!([
                    challenge.origin,
                    challenge.uri,
                    challenge.network,
                    challenge.public_key,
                    challenge.address,
                    challenge.nonce,
                    challenge.issued_at_ms,
                    challenge.expires_at_ms,
                ]),
            ),
            (
                Ok(_),
                Err(Error::InvalidSignIn {
                    problem: SignInProblem::Identity,
                }),
            ) if record.name.as_deref() == Some("another key's address") => Outcome::Divergent(
                "the wallet's check compares the address only with the identity it expects; the \
                 SDK also refuses an address that is not the key's",
            ),
            (Err(_), Err(Error::InvalidSignIn { .. })) => Outcome::Matched,
            (expected, actual) => Outcome::Failed(format!("expected {expected:?}, got {actual:?}")),
        }
    });
    assert_eq!(
        tally,
        Tally {
            matched: 34,
            divergent: 1,
            skipped: 0
        }
    );
}

// ------------------------------------------------------------------------------------------------
// Transactions and fee floors: S05 and S06, generated under the devnet chain of Heartwood Core's
// vectors. The requests are in the JSON the TypeScript wrapper passes to the core.

fn chain() -> &'static Chain {
    &DEVNET.chain
}

fn number<T: TryFrom<u64>>(value: &Value) -> T {
    let number = match value {
        Value::String(text) => text.parse::<u64>().expect("a decimal number"),
        other => other.as_u64().expect("a number"),
    };
    T::try_from(number).ok().expect("in range")
}

/// The account of a vector's signer: a legacy passphrase key, or a key derived from a phrase.
fn signer(spec: &Value) -> Account {
    let profile = chain().profile();
    match spec.get("mnemonic") {
        None => Account::from_legacy_passphrase(profile, text(&spec["passphrase"])),
        Some(mnemonic) => Account::from_phrase(
            profile,
            &Mnemonic::parse(text(mnemonic)).expect("a phrase"),
            &AccountOptions {
                account: number(&spec["account"]),
                index: number(&spec["index"]),
                passphrase: text(&spec["passphrase"]),
            },
        ),
    }
    .expect("a signer")
}

/// The operation of a request, from the wrapper's JSON.
fn operation(json: &Value) -> Operation {
    match text(&json["kind"]) {
        "transfer" => Operation::Transfer {
            recipients: json["to"]
                .as_array()
                .expect("recipients")
                .iter()
                .map(|to| Recipient {
                    address: Address::parse(text(&to["address"]), chain().profile())
                        .expect("an address"),
                    amount: Amount::from(number::<u64>(&to["amount"])),
                })
                .collect(),
        },
        "vote" => Operation::Vote {
            entries: json["entries"]
                .as_array()
                .expect("entries")
                .iter()
                .map(|entry| VoteEntry {
                    validator: text(&entry["validator"]).to_owned(),
                    basis_points: number(&entry["basisPoints"]),
                })
                .collect(),
        },
        "burn" => Operation::Burn {
            amount: Amount::from(number::<u64>(&json["amount"])),
        },
        "register-second-key" => Operation::RegisterSecondKey {
            public_key: PublicKeyBytes::from_hex(text(&json["publicKey"])).expect("a key"),
        },
        "register-validator" => Operation::RegisterValidator {
            name: text(&json["name"]).to_owned(),
        },
        "resign-validator" => Operation::ResignValidator {
            kind: match text(&json["resignation"]) {
                "temporary" => Resignation::Temporary,
                "permanent" => Resignation::Permanent,
                "revoke" => Resignation::Revoke,
                other => panic!("resignation {other}"),
            },
        },
        other => panic!("operation {other}"),
    }
}

/// A vector's draft: its request built with `fee` (the vector's own exact fee when `None`, or 1
/// for a request the reference refused), by the vector's signers.
struct Case {
    draft: Result<Draft, Error>,
    sender: Account,
    second: Option<Account>,
    aux: Aux,
}

fn case(record: &Record, fee: Option<FeeChoice>) -> Case {
    let input = &record.input;
    let request = &input["request"];
    let sender = signer(&input["signer"]);
    let second = input.get("secondSigner").map(signer);
    let fee = fee.unwrap_or_else(|| match request.get("fee") {
        Some(fee) => {
            assert_eq!(fee["kind"], "exact");
            FeeChoice::Exact(Amount::from(number::<u64>(&fee["amount"])))
        }
        None => FeeChoice::Exact(Amount::from(1u64)),
    });
    let draft_request = DraftRequest {
        operation: operation(&request["operation"]),
        memo: request["memo"].as_str().map(str::to_owned),
        fee,
    };
    let facts = &input["facts"];
    let online = OnlineFacts {
        sender: sender.public_key().clone(),
        nonce: number(&facts["nonce"]),
        height: number(&facts["height"]),
        second_key: facts
            .get("secondKey")
            .map(|key| PublicKey::from_hex(text(key)).expect("a key")),
    };
    if let Some(second) = &second {
        assert_eq!(Some(second.public_key()), online.second_key.as_ref());
    }
    Case {
        draft: Draft::build(chain(), &draft_request, &online),
        sender,
        second,
        aux: Aux::fixed(hex::decode_array(text(&input["aux"])).expect("32 bytes")),
    }
}

/// The SDK's refusal of a request the reference's builders refuse, by the reference's error.
fn refusal_code(class: &str) -> ErrorCode {
    match class {
        "MemoLengthExceededError" => ErrorCode::MemoTooLong,
        "MaximumTransferCountExceededError" => ErrorCode::TooManyRecipients,
        other => panic!("no SDK refusal is recorded for the reference's {other}"),
    }
}

#[test]
fn s05_transactions() {
    let file = load("S05-transactions");
    check_devnet(&file);
    let tally = run_class(&file, |record| {
        assert_eq!(record.op, "sdk.transaction");
        let Case {
            draft,
            sender,
            second,
            aux,
        } = case(record, None);
        match (&record.expected, draft) {
            (Ok(expected), Ok(draft)) => {
                let signed = match draft.sign_with(&sender, second.as_ref(), aux) {
                    Ok(signed) => signed,
                    Err(error) => return Outcome::Failed(format!("signing: {error}")),
                };
                if draft.size() != signed.bytes().len() || !signed.is_verified() {
                    return Outcome::Failed("the signed transaction is not the draft's".into());
                }
                compare(
                    expected,
                    &json!({
                        "unsigned": hex::encode(draft.unsigned_bytes()),
                        "size": draft.size(),
                        "id": signed.id(),
                        "hex": hex::encode(signed.bytes()),
                        "json": signed.json(),
                    }),
                )
            }
            (Err(error), Err(ours)) => {
                let expected = refusal_code(text(&error["class"]));
                if ours.code() == expected {
                    Outcome::Matched
                } else {
                    Outcome::Failed(format!("refused with {ours}, not {expected:?}"))
                }
            }
            (
                Ok(_),
                Err(Error::InvalidVote {
                    problem:
                        VoteProblem::TooManyEntries {
                            count: 54,
                            maximum: 53,
                        },
                }),
            ) => Outcome::Divergent(
                "the reference's builder writes a vote of more entries than there are seats, which \
                 its vote handler refuses when the transaction is applied; the SDK refuses it \
                 before anything is signed",
            ),
            (expected, actual) => Outcome::Failed(format!(
                "expected {expected:?}, got {:?}",
                actual.map(|draft| hex::encode(draft.unsigned_bytes()))
            )),
        }
    });
    assert_eq!(
        tally,
        Tally {
            matched: 25,
            divergent: 1,
            skipped: 0
        }
    );
}

#[test]
fn s06_fee_floor() {
    let file = load("S06-fee-floor");
    check_devnet(&file);
    assert!(
        chain().rules(2).fees.floor_available,
        "the build computes the exact fee floor"
    );
    let tally = run_class(&file, |record| {
        assert_eq!(record.op, "fee.floor");
        let expected = output(record);
        let Case { draft, .. } = case(record, None);
        let draft = match draft {
            Ok(draft) => draft,
            Err(error) => return Outcome::Failed(format!("refused: {error}")),
        };
        // The floor is a function of the size: the draft must be the reference's transaction.
        let built = json!({
            "unsigned": hex::encode(draft.unsigned_bytes()),
            "size": draft.size(),
        });
        let reference = json!({ "unsigned": expected["unsigned"], "size": expected["size"] });
        if let Outcome::Failed(message) = compare(&reference, &built) {
            return Outcome::Failed(message);
        }
        let floor = expected["floor"].clone();
        match chain().fee_floor(draft.kind(), draft.size(), record.height) {
            None => Outcome::Failed("no fee floor for this transaction".into()),
            Some(ours) => {
                if let Outcome::Failed(message) = compare(&floor, &json!(ours.to_string())) {
                    return Outcome::Failed(message);
                }
                // The default fee choice is the floor, and it builds the same transaction.
                let Case { draft: minimum, .. } = case(record, Some(FeeChoice::Minimum));
                match minimum {
                    Ok(minimum)
                        if minimum.fee().source == FeeSource::Floor
                            && minimum.fee().floor == Some(ours)
                            && minimum.fee().amount == ours
                            && minimum.unsigned_bytes() == draft.unsigned_bytes() =>
                    {
                        Outcome::Matched
                    }
                    other => Outcome::Failed(format!(
                        "the minimum fee is not the floor: {:?}",
                        other.map(|draft| draft.fee())
                    )),
                }
            }
        }
    });
    assert_eq!(file.records.len(), 114);
    assert_eq!(
        tally,
        Tally {
            matched: 114,
            divergent: 0,
            skipped: 0,
        }
    );
}

// ------------------------------------------------------------------------------------------------
// Ownership proofs: S08, with the verdicts of the legacy signer's own format checks and the
// reference's keys, Solar mainnet addresses and signatures.

/// The records the legacy signer accepts and the SDK refuses (in both `proof.build` and
/// `proof.parse` for the first): its format check reads the source address by its pattern only,
/// and the issue time with JavaScript's `Date.parse`; it reads a typed account with
/// JavaScript's Unicode `toLowerCase`. No signer makes such a proof for a real key and a real
/// time.
const STRICTER: [(&str, &str); 6] = [
    (
        "an S address of network byte 62",
        "the SDK also checks the source address's checksum and network byte 63",
    ),
    (
        "address with a bad checksum",
        "the SDK also checks the source address's checksum and network byte 63",
    ),
    (
        "issued on 30 February",
        "the SDK reads only real dates; Date.parse rolls the day over into March",
    ),
    (
        "issued on 29 February of a common year",
        "the SDK reads only real dates; Date.parse rolls the day over into March",
    ),
    (
        "issued at 24:00:00",
        "the SDK reads hours 0 to 23; Date.parse reads 24:00:00 as the next midnight",
    ),
    (
        "in capitals with a Kelvin sign for K",
        "the SDK refuses a typed account with a character outside ASCII; toLowerCase maps the \
         Kelvin sign to k",
    ),
];

/// The documented difference of `record`, if it is one the SDK refuses on purpose.
fn stricter(record: &Record) -> Option<&'static str> {
    let name = record.name.as_deref()?;
    STRICTER
        .iter()
        .find(|(case, _)| *case == name)
        .map(|(_, reason)| *reason)
}

fn proof_refused(record: &Record, result: Result<Value, Error>) -> Outcome {
    match (&record.expected, result) {
        (Ok(expected), Ok(actual)) => compare(expected, &actual),
        (Ok(_), Err(Error::InvalidProof { .. })) if stricter(record).is_some() => {
            Outcome::Divergent(stricter(record).expect("a reason"))
        }
        (Err(_), Err(Error::InvalidProof { .. })) => Outcome::Matched,
        (expected, actual) => Outcome::Failed(format!("expected {expected:?}, got {actual:?}")),
    }
}

#[test]
fn s08_ownership_proofs() {
    let file = load("S08-ownership-proofs");
    assert_eq!(
        file.meta["sourceNetworkByte"].as_u64(),
        Some(u64::from(ownership::SOLAR_NETWORK_BYTE))
    );
    let tally = run_class(&file, |record| {
        let input = &record.input;
        match record.op.as_str() {
            "proof.account" => proof_refused(
                record,
                IceRootAccount::parse(text(&input["text"])).map(|account| {
                    json!({ "account": account.as_str(), "network": account.network().as_str() })
                }),
            ),
            "proof.build" => {
                let built = (|| {
                    let address = Address::parse_any_network(text(&input["address"]))
                        .map_err(|_| Error::InvalidProof {
                            problem: iceroot_sdk_core::error::ProofProblem::Address,
                        })?;
                    let account = IceRootAccount::parse_canonical(text(&input["account"]))?;
                    ownership::build(&ProofRequest {
                        address: &address,
                        account: &account,
                        nonce: text(&input["nonce"]),
                        issued_at_ms: input["issuedAtMs"].as_i64().expect("a time"),
                    })
                })();
                proof_refused(record, built.map(|message| json!({ "message": message })))
            }
            "proof.parse" => {
                let expected = ProofExpected {
                    address: input["expected"].get("address").and_then(Value::as_str),
                };
                let now = input["now"].as_i64().expect("a time");
                let parsed = ownership::parse(text(&input["message"]), &expected, now);
                proof_refused(
                    record,
                    parsed.map(|fields| {
                        json!({
                            "network": ownership::SOURCE_NETWORK,
                            "address": fields.address,
                            "account": fields.account.as_str(),
                            "accountNetwork": fields.account.network().as_str(),
                            "nonce": fields.nonce,
                            "issuedAt": fields.issued_at,
                            "issuedAtMs": fields.issued_at_ms,
                        })
                    }),
                )
            }
            "proof.sign" => {
                let key = SolarKey::from_passphrase(text(&input["passphrase"])).expect("a key");
                let aux = Aux::fixed(hex::decode_array(text(&input["aux"])).expect("32 bytes"));
                let now = input["now"].as_i64().expect("a time");
                let signed = ownership::sign_with(&key, text(&input["message"]), now, aux);
                if let Ok(proof) = &signed {
                    // The JSON reads back as the same proof, which verifies.
                    let again = OwnershipProof::from_json(&proof.to_json()).expect("a proof");
                    if again != *proof || ownership::verify(proof, now).is_err() {
                        return Outcome::Failed("the signed proof does not read back".into());
                    }
                    // As made from the signature alone, the way a Ledger's signature is checked.
                    let from_signature = OwnershipProof::from_signature(
                        &proof.message,
                        &proof.public_key,
                        &proof.signature,
                        now,
                    );
                    if from_signature.as_ref() != Ok(proof) {
                        return Outcome::Failed(format!("from_signature gives {from_signature:?}"));
                    }
                }
                proof_refused(
                    record,
                    signed.map(|proof| {
                        json!({ "proof": proof.to_json_value(), "json": proof.to_json() })
                    }),
                )
            }
            "proof.verify" => {
                let now = input["now"].as_i64().expect("a time");
                let verdict = OwnershipProof::from_json_value(&input["proof"])
                    .and_then(|proof| ownership::verify(&proof, now));
                compare(output(record), &json!({ "valid": verdict.is_ok() }))
            }
            other => Outcome::Failed(format!("unknown operation {other}")),
        }
    });
    assert_eq!(
        tally,
        Tally {
            matched: 112,
            divergent: 7,
            skipped: 0
        }
    );
}

#[test]
fn every_class_is_run() {
    let mut classes: Vec<String> = std::fs::read_dir(vectors_dir().join("sdk"))
        .expect("the SDK vectors")
        .map(|entry| {
            entry
                .expect("an entry")
                .file_name()
                .to_string_lossy()
                .into_owned()
        })
        .filter_map(|name| name.strip_suffix(".jsonl").map(str::to_owned))
        .collect();
    classes.sort();
    assert_eq!(
        classes,
        [
            "S01-phrases",
            "S02-derivation",
            "S03-messages",
            "S04-signin",
            "S05-transactions",
            "S06-fee-floor",
            // Run by the keystore's own tests (crates/iceroot-keystore/tests/vectors.rs).
            "S07-keystore",
            "S08-ownership-proofs",
        ],
        "a vector class without a test"
    );
}
